
IF @@TRANCOUNT > 0 COMMIT TRANSACTION;

/****** Object:  FullTextCatalog [AW2008FullTextCatalog]    Script Date: 11/23/2013 12:18:27 ******/

CREATE FULLTEXT CATALOG [AW2008FullTextCatalog]WITH ACCENT_SENSITIVITY = ON
AS DEFAULT
AUTHORIZATION [dbo]
GO

